version: "3"
services:
    app1:
        build: ./app1
        container_name: app1
        ports: 
            - "3001:3000"
    app2:
        build: ./app2
        container_name: app2
        ports: 
            - "3002:3000"
    app3:
        build: ./app3
        container_name: app3
        ports: 
            - "3003:3000"
    app4:
        build: ./app4
        container_name: app4
        ports: 
            - "3004:3000"
    app5:
        build: ./app5
        container_name: app5
        ports: 
            - "3005:3000"
    nginx:
        image: nginx
        container_name: nginx
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
networks:
  default:
    external:
      name: load-balance-random