version: "3"
services:
    app1:
        build: ./app1
        container_name: app1
        ports: 
            - "3001:3000"
    app2:
        build: ./app2
        container_name: app2
        ports: 
            - "3002:3000"
    nginx:
        image: nginx
        container_name: nginx
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
networks:
  default:
    external:
      name: load-balance-least-connection